# Generated by Django 5.0.1 on 2024-03-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_course_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudent',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='allstudent',
            name='per_month_installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='allstudent',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
