# Generated by Django 5.0.1 on 2024-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_allstudent_total_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudent',
            name='total_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
