# Generated by Django 5.0.1 on 2024-03-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_allstudent_total_paid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstudent',
            old_name='total_paid_amount',
            new_name='paid_amount',
        ),
    ]
