# Generated by Django 5.0.1 on 2024-03-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_installment_comment_installment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
