# Generated by Django 5.0.1 on 2024-03-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_installment_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstudent',
            old_name='paid_amount',
            new_name='total_paid_amount',
        ),
    ]
