# Generated by Django 5.0.1 on 2024-03-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_rename_total_payment_amount_allstudent_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudent',
            name='extra_installments_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
