# Generated by Django 5.0.1 on 2024-03-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_allstudent_extra_installments_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstudent',
            name='extra_installments_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
