# Generated by Django 5.0.1 on 2024-03-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_allstudent_payment_date_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allstudent',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='allstudent',
            name='extra_installments_paid',
        ),
        migrations.RemoveField(
            model_name='allstudent',
            name='payment_date_discount',
        ),
    ]
