# Generated by Django 5.0.1 on 2024-03-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_allstudent_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudent',
            name='extra_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
