# Generated by Django 5.0.1 on 2024-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_allstudent_total_payable_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
