# Generated by Django 5.0.1 on 2024-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_installment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allstudent',
            name='total_payable_amount',
        ),
        migrations.AlterField(
            model_name='installment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
