# Generated by Django 5.0.1 on 2024-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_allstudent_total_payable_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
