# Generated by Django 5.0.1 on 2024-03-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_installment_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstudent',
            name='total_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
