# Generated by Django 5.0.3 on 2024-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_allstudent_class_or_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstudent',
            name='extra_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
